#ifndef BT_PLANT_PGIN_GLOBAL_H
#define BT_PLANT_PGIN_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(BT_PLANT_PGIN_LIBRARY)
#  define BT_PLANT_PGINSHARED_EXPORT Q_DECL_EXPORT
#else
#  define BT_PLANT_PGINSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // BT_PLANT_PGIN_GLOBAL_H
