#ifndef BT_SCS_BUS_PGIN_GLOBAL_H
#define BT_SCS_BUS_PGIN_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(BT_SCS_BUS_PGIN_LIBRARY)
#  define BT_SCS_BUS_PGINSHARED_EXPORT Q_DECL_EXPORT
#else
#  define BT_SCS_BUS_PGINSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // BT_SCS_BUS_PGIN_GLOBAL_H
